
        platform: linux
        image_resource:
          type: docker-image
          source: 
            repository: mcr.microsoft.com/dotnet/sdk
            tag: '8.0'
        inputs: 
        - name: source-code
        run:
          path: sh
          args:
          - -exec
          - |
            dotnet build ./source-code/src/eShopOnDotNet.sln